### ISSUE TITLE
Can't see the list of services

### ISSUE THREAD

**Issue by timgent** [UKHomeOffice/coe#11]
The github pages main page has some broken links on it, and some just link back to the same page. I can no longer see the list of services.

2 points here:
1) Would be good if changes can be reviewed before merging (can we protect the master branch from direct pushes without PR)
2) Can someone fix this issue in the meantime?

**Comment by owenm6** [comment]
@timgent It's fixed now.

**Comment by easternbloc** [comment]
@owenm6 if it's fixed it hasn't been released yet. I just looked and there are still a load of broken links on the main page...

**Comment by owenm6** [comment]
Locally it was fixed. Hold on...

**Comment by owenm6** [comment]
OK now its fixed. Apologies.
